### ISSUE TITLE
Certificate problem override

### ISSUE THREAD

**Issue by drwetter** [JavanXD/Typo3AccessChecker#3]
Hi

thanks for the useful tool!  It helped me fingerprint a web site which I wasn't able to do otherwise with a few other existing tools.

I ran it also on a web site I have access to. It didn't work though because "they" messed up the certificates. In this context it was good because I realized that was wrong and corrected it. 

But in general it would be great to have a flag overriding such problems.

Thx, Dirk

**Comment by JavanXD** [comment]
What was the error message?

**Comment by drwetter** [comment]
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='REDACTED', port=443): Max retries exceeded with url: /thispagedoesnotexist (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
``

**Comment by JavanXD** [comment]
Closed, because overriding ssl cert errors is not a good practice. Else the error wouldn't be recognised.

**Comment by drwetter** [comment]
What? I think you're missing the general point of security assessment tools.

Please read carefully my request again. I was not aiming reducing any security in general. I just suggested to have a flag to override such problems.

**Comment by JavanXD** [comment]
@drwetter To test your websites ssl certificates I highly recommend using https://testssl.sh/

**Comment by drwetter** [comment]
You bet I do all the time. I am the author.

**Comment by JavanXD** [comment]
@drwetter okay Dirk, that is a funny blunder. I am going to add that override flag :-)

**Comment by drwetter** [comment]
👍
