### ISSUE TITLE
Content Length

### ISSUE THREAD

**Issue by drwetter** [JavanXD/Typo3AccessChecker#4]
I had one 200 which returned ``Content-Length: 0`` which was ``$DOMAIN /typo3conf/LocalConfiguration.php``.

How about checking the content-length?

**Comment by JavanXD** [comment]
content-length 0 and status-code 200 would mean "It is possible to access a php file directly."
Should be part of your report.

**Comment by drwetter** [comment]
yeah, but it's normal that it doesn't return anything, e.g https://docs.typo3.org/m/typo3/reference-inside/8.7/en-us/CoreArchitecture/Configuration/LocalConfiguration/Index.html

Other files might have a handler that it prevents from being executed directly. IIRC you also get a zero length returned.

**Comment by drwetter** [comment]
Same with ``$DOMAIN/typo3conf/AdditionalConfiguration.php`` if it exists. 

<s>https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/GlobalValues/Typo3ConfVars/Index.html</s>

A ``Content-Length: 0`` is probably good indicator that one really has hit a Typo3 system -- same as looking at the HTML of ``/``. But it is not a finding.

**Comment by JavanXD** [comment]
Closed,
Status-Code 200 AND Content-Length: 0 => means you have accessed a PHP file (without any echo) directly. E.g. a include/require_once dependency. This kind of access should be blocked in .htaccess.
